[project]
name = "rl-gomoku"
version = "0.1.0"
description = "Gomoku game with RL Logic for COMP0215"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pygame>=2.6.1",
    "torch>=2.11.0",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
